const QUESTIONS = [
  {
    q: "¿Qué significa VIAM-Medical?",
    options: [
      "Visual Intelligent Artificial Medical",
      "Virtual Imaging and Automation Medical",
      "Vital Integrated Android Machine",
      "Vision Interface for Advanced Medicine",
    ],
    a: 0,
    explain: "V = Visual, I = Intelligent, A = Artificial y M = Medical.",
  },
  {
    q: "¿En qué colegio y país se desarrolla el proyecto?",
    options: [
      "Colegio Don Bosco, Soyapango, El Salvador",
      "Instituto Técnico Ricaldone, San Salvador",
      "Colegio Externado, Guatemala",
      "Universidad Nacional, Honduras",
    ],
    a: 0,
    explain: "3.er año de Electrónica del Colegio Don Bosco, Soyapango.",
  },
  {
    q: "¿Para qué evento se creó VIAM-Medical?",
    options: ["CREA-J 2026", "Science Fair 2024", "NASA Challenge", "FIRST Robotics 2025"],
    a: 0,
    explain: "Primera Evaluación CREA-J 2026 de Inglés Técnico.",
  },
  {
    q: "¿Quién es Ícaro en el proyecto?",
    options: [
      "El robot de datos de la sala de espera",
      "El ecógrafo portátil",
      "El estetoscopio digital",
      "Una app de citas médicas",
    ],
    a: 0,
    explain: "Ícaro es el personaje de datos: registra, mide temperatura y baja la saturación.",
  },
  {
    q: "¿Qué hace Ícaro en la sala de espera?",
    options: [
      "Registra datos del paciente, toma temperatura IR y puede ayudar a trasladarlo",
      "Opera a los pacientes",
      "Vende medicinas",
      "Solo muestra videos",
    ],
    a: 0,
    explain: "Así el personal atiende, no hace fila.",
  },
  {
    q: "¿Cómo corre la IA de Ícaro?",
    options: [
      "En local, sin depender de internet",
      "Solo en la nube de Google",
      "En un celular del paciente",
      "No usa inteligencia artificial",
    ],
    a: 0,
    explain: "IA embebida: privacidad y clínicas con mala conexión.",
  },
  {
    q: "¿Cómo toma Ícaro la temperatura?",
    options: [
      "Sin contacto, con sensor infrarrojo",
      "Con un termómetro de mercurio",
      "Preguntando si tiene fiebre",
      "Con el estetoscopio Pulse",
    ],
    a: 0,
    explain: "Sensor térmico IR, rápido y seguro.",
  },
  {
    q: "¿Qué problema busca bajar Ícaro en el hospital?",
    options: [
      "La saturación de la sala de espera",
      "El precio de las ambulancias",
      "La falta de sillas",
      "El inventario de jeringas",
    ],
    a: 0,
    explain: "Si el registro se adelanta, la consulta avanza.",
  },
  {
    q: "¿Cuántas unidades inteligentes tiene VIAM-Medical además de Ícaro?",
    options: [
      "Dos: Vision (ultrasonido) y Pulse (estetoscopio digital)",
      "Tres: Heart, Lung y Brain",
      "Una sola estación",
      "Cuatro sensores sueltos",
    ],
    a: 0,
    explain: "Vision ve por dentro. Pulse escucha corazón y pulmón.",
  },
  {
    q: "¿Qué hace el módulo Pulse?",
    options: [
      "Estetoscopio digital que captura sonidos de corazón y pulmón",
      "Cámara térmica para fiebre",
      "Medidor de glucosa",
      "Robot que opera",
    ],
    a: 0,
    explain: "Audio en tiempo real y clasificación con IA.",
  },
  {
    q: "¿Qué hace el módulo Vision?",
    options: [
      "Ecógrafo portátil de hardware abierto, guiado por IA",
      "Gafas de realidad virtual",
      "Escáner de huellas",
      "Microscopio dental",
    ],
    a: 0,
    explain: "Convierte ecos de ultrasonido en imagen.",
  },
  {
    q: "¿Qué problema principal cierra el proyecto?",
    options: [
      "La falta de diagnóstico avanzado en clínicas rurales y comunitarias",
      "El precio de las ambulancias",
      "La falta de cirujanos",
      "El inventario de medicinas",
    ],
    a: 0,
    explain: "En El Salvador el equipo de imagen está en hospitales urbanos caros.",
  },
  {
    q: "¿Cuánto cuesta aproximadamente un ecógrafo comercial, según el informe?",
    options: ["Más de $30,000 USD", "$2,000 USD", "$150 USD", "$9,999 USD"],
    a: 0,
    explain: "Ese precio deja la imagen solo en hospitales grandes.",
  },
  {
    q: "¿Cuál es el costo total de materiales de VIAM-Medical?",
    options: ["$674.64 USD", "$3,200 USD", "$12,450 USD", "$99.99 USD"],
    a: 0,
    explain: "Se puede replicar en entornos de bajos recursos.",
  },
  {
    q: "¿Qué frecuencia tiene el transductor de ultrasonido?",
    options: ["3.5 MHz", "2.4 GHz", "440 Hz", "60 kHz"],
    a: 0,
    explain: "Transductor de 3.5 MHz con la placa pic0rick.",
  },
  {
    q: "¿Qué placa de hardware abierto usa Vision?",
    options: ["pic0rick", "Arduino Uno", "NVIDIA Jetson", "Raspberry Pi Pico W"],
    a: 0,
    explain: "pic0rick es un sistema pulse-echo abierto para ultrasonido.",
  },
  {
    q: "¿Qué microcontrolador trae pic0rick?",
    options: ["RP2040", "ATmega328P", "ESP8266", "STM32H7"],
    a: 0,
    explain: "RP2040, ADC rápido y Time Gain Control.",
  },
  {
    q: "¿Qué modelo de IA clasifica los sonidos en Pulse?",
    options: ["YAMNet", "ChatGPT", "YOLO v8", "Whisper"],
    a: 0,
    explain: "YAMNet + una red local detecta soplos y anomalías.",
  },
  {
    q: "¿Por qué la IA corre en el dispositivo y no solo en la nube?",
    options: [
      "Para proteger la privacidad y no depender de internet estable",
      "Porque la nube es ilegal",
      "Porque YAMNet no funciona en servidores",
      "Para que el robot hable más rápido",
    ],
    a: 0,
    explain: "Inferencia local: privacidad y clínicas con mala red.",
  },
  {
    q: "¿Qué plataforma orquesta el hardware?",
    options: ["Viam", "Unity", "WordPress", "Docker Desktop"],
    a: 0,
    explain: "El nombre VIAM también evoca la plataforma Viam.",
  },
  {
    q: "¿VIAM-Medical pretende reemplazar los equipos de hospital?",
    options: [
      "No: busca un primer tamizaje cercano y una mejor referencia",
      "Sí: sustituye por completo al ecógrafo de hospital",
      "Sí: opera sin personal de salud",
      "No: solo es un juguete de feria",
    ],
    a: 0,
    explain: "Si la clínica detecta algo a tiempo, el paciente viaja mejor informado.",
  },
  {
    q: "¿Qué valor social destaca el informe?",
    options: [
      "Democratizar el diagnóstico: dignidad, no poder de compra",
      "Vender el robot a hospitales privados",
      "Reemplazar a las enfermeras",
      "Ganar un concurso de videojuegos",
    ],
    a: 0,
    explain: "Espíritu salesiano del Don Bosco: la ciencia al servicio de los más vulnerables.",
  },
  {
    q: "¿Qué idea resume la soberanía tecnológica del proyecto?",
    options: [
      "Hardware y software abiertos para mantenerlo y mejorarlo en el país",
      "Comprar licencias extranjeras cada año",
      "Prohibir el uso de Raspberry Pi",
      "Esconder el código del prototipo",
    ],
    a: 0,
    explain: "Menos dependencia de licencias y más talento local.",
  },
  {
    q: "Si hay conectividad, ¿qué abre la plataforma Viam?",
    options: [
      "Teleconsulta con especialistas",
      "Compras de medicinas en línea",
      "Streaming de películas",
      "Minería de criptomonedas",
    ],
    a: 0,
    explain: "No es un aparato aislado: puede conectar la clínica con un especialista.",
  },
];
